### ISSUE TITLE
Getting a Panda error

### ISSUE THREAD

**Issue by geoffro10** [mbillow/ha-chargepoint#11]
Hello,

I'm seeing this warning in the HA logs. Not sure if it's anything to be concerned with but thought I'd share here to see.

2022-07-31 18:43:25 WARNING (SyncWorker_6) [chargepoint] Panda technical information did not include device IP.

**Comment by mbillow** [comment]
ChargePoint, in their API, calls their home charging devices Pandas. Sometimes, for unknown reasons, their API just doesn’t include the IP of the charger. It doesn’t impact Home Assistant because the module doesn’t use the IP field. You can safely ignore it or disable it by setting the ChargePoint logger’s level to `ERROR`.
